### ISSUE TITLE
Help, I cannot remember why I wanted to run the simulation with predictor correlations set to zero.

### ISSUE THREAD

**Issue by hanneoberman** [gerkovink/shinyMice#6]
Hi! In one of the MICE meetings we have discussed running my simulation on convergence with very low or even with no correlations between the predictor variables in the analysis. The problem is that I do not remember whether this was related the the actual performance of $\widehat{R}$, or only for me to find out what would happen with respect to the theoretically implausible values below one that I kept getting. Because I did do so now, but nothing interesting happened. @gerkovink @stefvanbuuren can you enlighten me? (I'll ask you on Monday anyways)

**Comment by stefvanbuuren** [comment]
I would expect that convergence is immediate if correlations are near zero. Correlations near one would result in slow convergence. It would be interesting of the statistic can pick this up.

**Comment by hanneoberman** [comment]
> I expect that convergence is immediate if correlations are near zero. Correlations near one result in slow convergence. It would be interesting of the statistic can pick this up.

Thank you! At first glance it didn't, but I'll run some more sims.
